version: '3'
volumes:
  data-volume: {}
services:
  nginx:
   container_name: some-nginx
   image: nginx:alpine
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
   command: [nginx-debug, '-g', 'daemon off;']
   depends_on:
     - app

  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   hostname: mysql
   ports:
   - "3306:3306"
   volumes:
      - data-volume:/var/lib/mysql3
      - ./SQLSchema/dumps/26_03_dump.sql:/docker-entrypoint-initdb.d/26_03_dump.sql
   command: mysqld --sql_mode=""
   environment:
     MYSQL_DATABASE: classification
     MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASS}
     MYSQL_ROOT_HOST: '%'
   restart: always
  app:
    restart: always
    hostname: taxonomy-tool
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    env_file:
      - .env
    command: /go/src/github/mr-ma/paper-review-go/taxonomyserver -mysqluser root -mysqlpass ${ENV_MYSQL_ROOT_PASS} -mysqlserver mysql:3306 -listen 0.0.0.0:8081
    depends_on:
      - mysql
    links:
      - mysql
