version: '3'
volumes:
  data-volume: {}
services:
  nginx:
   container_name: jen-nginx
   image: nginx:alpine
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
     - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./statics:/etc/nginx/statics:ro
   command: [nginx-debug, '-g', 'daemon off;']
   depends_on:
     - taxonomy-builder
     - analysis
     - lit-importer
     - user-management
     - paper-review
  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   hostname: mysql
   ports:
   - "3306:3306"
   volumes:
      - data-volume:/var/lib/mysql5
      - ./SQLSchema/dumps/26_03_dump.sql:/docker-entrypoint-initdb.d/26_03_dump.sql
   env_file:
     - .env
   restart: always
  taxonomy-builder:
    container_name: some-taxonomy-builder
    restart: always
    hostname: taxonomy-builder
    build: .
    ports:
      - "8086:8086"
    expose:
      - "8086"
    env_file:
      - .env
    command: /go/src/github/mr-ma/paper-review-go/server/taxonomy-builder-server -mysqluser root -mysqlpass ${MYSQL_ROOT_PASSWORD} -mysqlserver mysql:3306 -listen 0.0.0.0:8086
    depends_on:
      - mysql
    links:
      - mysql
  analysis:
    container_name: some-analysis
    restart: always
    hostname: analysis
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    env_file:
      - .env
    command: /go/src/github/mr-ma/paper-review-go/server/analysis-server -mysqluser root -mysqlpass ${MYSQL_ROOT_PASSWORD} -mysqlserver mysql:3306 -listen 0.0.0.0:8081
    depends_on:
      - mysql
    links:
      - mysql

  lit-importer:
    container_name: some-lit-importer
    restart: always
    hostname: lit-importer
    build: .
    ports:
      - "8085:8085"
    expose:
      - "8085"
    env_file:
      - .env
    command: /go/src/github/mr-ma/paper-review-go/server/lit-importer-server -mysqluser root -mysqlpass ${MYSQL_ROOT_PASSWORD} -mysqlserver mysql:3306 -listen 0.0.0.0:8085
    depends_on:
      - mysql
    links:
      - mysql

  user-management:
    container_name: some-user-management
    restart: always
    hostname: user-management
    build: .
    ports:
      - "8082:8082"
    expose:
      - "8082"
    env_file:
      - .env
    command: /go/src/github/mr-ma/paper-review-go/server/user-management-server -mysqluser root -mysqlpass ${MYSQL_ROOT_PASSWORD} -mysqlserver mysql:3306 -listen 0.0.0.0:8082
    depends_on:
      - mysql
    links:
      - mysql

  paper-review:
    container_name: some-paper-view
    restart: always
    hostname: paper-review
    build: .
    ports:
      - "8083:8083"
    expose:
      - "8083"
    env_file:
      - .env
    command: /go/src/github/mr-ma/paper-review-go/server/review-server -mysqluser root -mysqlpass ${MYSQL_ROOT_PASSWORD} -mysqlserver mysql:3306 -listen 0.0.0.0:8083
    depends_on:
      - mysql
    links:
      - mysql
